  DataCollector.cpp
c:\users\kevin\documents\github\conuhacks2016\myocontroller\myocontroller\myo\cxx\impl\../detail/ThrowOnError.hpp(39): warning C4297: 'myo::ThrowOnError::~ThrowOnError': function assumed not to throw an exception but does
  c:\users\kevin\documents\github\conuhacks2016\myocontroller\myocontroller\myo\cxx\impl\../detail/ThrowOnError.hpp(39): note: destructor or deallocator has a (possibly implicit) non-throwing exception specification
c:\users\kevin\documents\github\conuhacks2016\myocontroller\myocontroller\myo\cxx\impl\../detail/ThrowOnError.hpp(45): warning C4297: 'myo::ThrowOnError::~ThrowOnError': function assumed not to throw an exception but does
  c:\users\kevin\documents\github\conuhacks2016\myocontroller\myocontroller\myo\cxx\impl\../detail/ThrowOnError.hpp(45): note: destructor or deallocator has a (possibly implicit) non-throwing exception specification
c:\users\kevin\documents\github\conuhacks2016\myocontroller\myocontroller\ServerClient.h(128): warning C4267: 'initializing': conversion from 'size_t' to 'unsigned int', possible loss of data
  main.cpp
c:\users\kevin\documents\github\conuhacks2016\myocontroller\myocontroller\myo\cxx\impl\../detail/ThrowOnError.hpp(39): warning C4297: 'myo::ThrowOnError::~ThrowOnError': function assumed not to throw an exception but does
  c:\users\kevin\documents\github\conuhacks2016\myocontroller\myocontroller\myo\cxx\impl\../detail/ThrowOnError.hpp(39): note: destructor or deallocator has a (possibly implicit) non-throwing exception specification
c:\users\kevin\documents\github\conuhacks2016\myocontroller\myocontroller\myo\cxx\impl\../detail/ThrowOnError.hpp(45): warning C4297: 'myo::ThrowOnError::~ThrowOnError': function assumed not to throw an exception but does
  c:\users\kevin\documents\github\conuhacks2016\myocontroller\myocontroller\myo\cxx\impl\../detail/ThrowOnError.hpp(45): note: destructor or deallocator has a (possibly implicit) non-throwing exception specification
c:\users\kevin\documents\github\conuhacks2016\myocontroller\myocontroller\ServerClient.h(128): warning C4267: 'initializing': conversion from 'size_t' to 'unsigned int', possible loss of data
main.cpp(28): warning C4297: 'SDL_main': function assumed not to throw an exception but does
  main.cpp(28): note: __declspec(nothrow), throw(), noexcept(true), or noexcept was specified on the function
  WifiDataCollector.cpp
c:\users\kevin\documents\github\conuhacks2016\myocontroller\myocontroller\myo\cxx\impl\../detail/ThrowOnError.hpp(39): warning C4297: 'myo::ThrowOnError::~ThrowOnError': function assumed not to throw an exception but does
  c:\users\kevin\documents\github\conuhacks2016\myocontroller\myocontroller\myo\cxx\impl\../detail/ThrowOnError.hpp(39): note: destructor or deallocator has a (possibly implicit) non-throwing exception specification
c:\users\kevin\documents\github\conuhacks2016\myocontroller\myocontroller\myo\cxx\impl\../detail/ThrowOnError.hpp(45): warning C4297: 'myo::ThrowOnError::~ThrowOnError': function assumed not to throw an exception but does
  c:\users\kevin\documents\github\conuhacks2016\myocontroller\myocontroller\myo\cxx\impl\../detail/ThrowOnError.hpp(45): note: destructor or deallocator has a (possibly implicit) non-throwing exception specification
c:\users\kevin\documents\github\conuhacks2016\myocontroller\myocontroller\ServerClient.h(128): warning C4267: 'initializing': conversion from 'size_t' to 'unsigned int', possible loss of data
  Generating code
  426 of 429 functions (99.3%) were compiled, the rest were copied from previous compilation.
    0 functions were new in current compilation
    0 functions had inline decision re-evaluated but remain unchanged
  Finished generating code
  MyoController.vcxproj -> C:\Users\kevin\Documents\GitHub\conuhacks2016\MyoController\x64\Release\MyoController.exe
  MyoController.vcxproj -> C:\Users\kevin\Documents\GitHub\conuhacks2016\MyoController\x64\Release\MyoController.pdb (Full PDB)
